### ISSUE TITLE
デザイン2パターンの方針決め

### ISSUE THREAD

**Issue by shoprog** [tsukiji-club/FrontEnd#1]
TOPページに置こうと思っている各メニューとWORKS画像の構成案を2パターン作って比較したいと思います。

TODO
----

- [ ] パターンA
- [ ] パターンB

**Comment by dev-tsukiji** [comment]
マークダウンは**Previewタグ**で確認できます。

**Comment by dev-tsukiji** [comment]
Aパターンが良いです。

**Comment by shoprog** [comment]
では、Aパターンで進めます。
